{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deputies.postgresSecretName" . }}
  labels:
    {{- include "deputies.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgres.username | quote }}
  password: {{ .Values.postgres.password | quote }}
  database: {{ .Values.postgres.database | quote }}
  host: {{ .Values.postgres.host | quote }}
  port: {{ .Values.postgres.port | quote }}
{{- end }}
