{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.credentials.secretName }}
  labels:
    {{- include "deputies-platform-reference.labels" . | nindent 4 }}
    {{- with .Values.postgresql.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.postgresql.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  username: {{ .Values.postgresql.credentials.username | quote }}
  password: {{ .Values.postgresql.credentials.password | quote }}
  postgres-password: {{ .Values.postgresql.credentials.password | quote }}
  database: {{ .Values.postgresql.credentials.database | quote }}
  host: {{ .Values.postgresql.service.name | quote }}
  port: {{ .Values.postgresql.service.port | quote }}
  sslmode: "disable"
{{- end }}
