{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.service.name }}
  labels:
    {{- include "deputies-platform-reference.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
    {{- with .Values.postgresql.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.postgresql.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: postgres
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgres
  selector:
    {{- include "deputies-platform-reference.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
